name: DotMH Shared Set Actions
on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: '8'
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.15.0'
          cache: 'pnpm'
      - run: pnpm install
