name: DotMH Test Actions
run-name: ${{ github.actor }} - ${{ github.workflow }} - ${{ github.run_number }}
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.15.0'
      - run: npm install -g pnpm@8
      - run: pnpm install
      - run: pnpm test
